name: 'mirror'
on:
  push:
    branches:
        - __mirror
  schedule:
    # Run everyday at 3 AM UTC
    - cron: '* 2/* * * *'
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    name: mirror
    steps:
      - name: mirror
        id: mirror
        uses: bridgelightcloud/github-mirror-action@v2
        with:
          origin: 'https://r8.googlesource.com/r8'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
